# Define codons used by D. discoideum

Lys <- c('AAA', 'AAG')
Ala <- c('GCT', 'GCC', 'GCG', 'GCA')
Phe <- c('TTT', 'TTC')
Leu <- c('TTA', 'TTG', 'CTT', 'CTC', 'CTA', 'CTG')
Ile <- c('ATT', 'ATC', 'ATA')
Met <- c('ATG')
Val <- c('GTT', 'GTC', 'GTA', 'GTG')
Ser <- c('TCT', 'TCC', 'TCA', 'TCG', 'AGT', 'AGC')
Pro <- c('CCT', 'CCC', 'CCA', 'CCG')
Thr <- c('ACT', 'ACC', 'ACA', 'ACG')
Tyr <- c('TAT', 'TAC')
Stop <- c('TAA', 'TAG', 'TGA')
His <- c('CAT', 'CAC')
Gln <- c('CAA', 'CAG')
Asn <- c('AAT', 'AAC')
Asp <- c('GAT', 'GAC')
Glu <- c('GAA', 'GAG')
Cys <- c('TGT', 'TGC')
Trp <- c('TGG')
Arg <- c('CGT', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG')
Gly <- c('GGT', 'GGC', 'GGA', 'GGG')

aa.all <- c(Lys, Ala, Phe, Leu, Ile, Met, Val, Ser, Pro, Thr, Tyr, Stop, His, Gln, Asn, Asp, Glu, Cys, Trp, Arg, Gly)
aa.names <- c('Lys', 'Ala', 'Phe', 'Leu', 'Ile', 'Met', 'Val', 'Ser', 'Pro', 'Thr', 'Tyr', 'His', 'Gln', 'Asn', 'Asp', 'Glu', 'Cys', 'Trp', 'Arg', 'Gly')